#!/bin/zsh

## ---
## The function whichhostname() checks if the given hostname matches the ones
## of the current machine. If so returns 0 (process successfull exit code)
## otherwise it return 1 (process failure exit code).
##
## The function is useful to source settings file conditionally.
##

whichhostname () {
    local hostname=$1

    local detected_hostname=$(uname -n)

    [[ $detected_platform:l == $platform:l && $detected_hostname:l =~ $hostname:l ]] && return 0;

    return 1;
}
